.TH "apps/Emma-Rest6/Emma-interpreteur.c" 3 "22 Jun 2010" "Version 0.2" "EMMA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apps/Emma-Rest6/Emma-interpreteur.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Emma-Rest6.h'\fP
.br

.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum { \fBAND\fP, \fBOR\fP, \fBINF\fP, \fBSUP\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBgetOperande\fP (char *str, char *op, char *opd1, char *opd2, int size)"
.br
.ti -1c
.RI "int \fBEmmal_evaluate\fP (char *str)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Header file of EMMA interpreter for EMMALanguage 
.PP
\fBAuthor:\fP
.RS 4
Clement DUHART <duhart.clement@gmail.com> 
.RE
.PP

.PP
Definition in file \fBEmma-interpreteur.c\fP.
.SH "Author"
.PP 
Generated automatically by Doxygen for EMMA from the source code.
