.TH "apps/Emma-Rest6/Emma-conf.h" 3 "22 Jun 2010" "Version 0.2" "EMMA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apps/Emma-Rest6/Emma-conf.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBDEBUG\fP   1"
.br
.ti -1c
.RI "#define \fBSEND_NOTIFY\fP   1"
.br
.ti -1c
.RI "#define \fBPORT\fP   80"
.br
.ti -1c
.RI "#define \fBPROCESS_TIME\fP   3"
.br
.ti -1c
.RI "#define \fBPROCESS_TIME_LOG\fP   5"
.br
.ti -1c
.RI "#define \fBPROCESS_TIME_REPORT\fP   5"
.br
.ti -1c
.RI "#define \fBRESSOURCE_NAME_SIZE\fP   12"
.br
.ti -1c
.RI "#define \fBRESSOURCE_ID_MAX_DIGIT\fP   3"
.br
.ti -1c
.RI "#define \fBBODY_NOTIFY\fP   18"
.br
.ti -1c
.RI "#define \fBURI_OUTCOMMING_MAX_SIZE\fP   (15 + RESSOURCE_NAME_SIZE + RESSOURCE_ID_MAX_DIGIT)"
.br
.ti -1c
.RI "#define \fBURI_INCOMMING_MAX_SIZE\fP   (15 + RESSOURCE_NAME_SIZE + RESSOURCE_ID_MAX_DIGIT)"
.br
.ti -1c
.RI "#define \fBBUFFER_SIZE\fP   70"
.br
.ti -1c
.RI "#define \fBBUFFER_SOCKET_SIZE\fP   70"
.br
.ti -1c
.RI "#define \fBBUFFERMINI_SIZE\fP   6"
.br
.ti -1c
.RI "#define \fBINCOMMING_CONNECTION_MAX\fP   1"
.br
.ti -1c
.RI "#define \fBOUTCOMMING_CONNECTION_MAX\fP   1"
.br
.ti -1c
.RI "#define \fBTIMEOUT\fP   20"
.br
.ti -1c
.RI "#define \fBREPORT_CMD_SIZE\fP   20"
.br
.in -1c
.SH "Detailed Description"
.PP 
Configuration file of EMMA-Rest6 Engine 
.PP
\fBAuthor:\fP
.RS 4
Clement DUHART <duhart.clement@gmail.com>
.RE
.PP
This file contains all the static configuration of Emma-Rest6 Engine. 
.PP
Definition in file \fBEmma-conf.h\fP.
.SH "Author"
.PP 
Generated automatically by Doxygen for EMMA from the source code.
