.TH "platform/avr-meshnectics/loadable_prg.c" 3 "22 Jun 2010" "Version 0.2" "EMMA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
platform/avr-meshnectics/loadable_prg.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio.h>\fP
.br
\fC#include 'dev/rs232.h'\fP
.br
\fC#include 'contiki.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBPROCESS\fP (test_process1,'Test process')"
.br
.ti -1c
.RI "\fBPROCESS_THREAD\fP (test_process1, ev, data)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "CLIF struct process *const \fBautostart_processes\fP [] = {&test_process1}"
.br
.in -1c
.SH "Detailed Description"
.PP 
Sample loadable module
.PP
\fBAuthor:\fP
.RS 4
Simon Barner <barner@in.tum.de> 
.RE
.PP

.PP
Definition in file \fBloadable_prg.c\fP.
.SH "Author"
.PP 
Generated automatically by Doxygen for EMMA from the source code.
