.TH "Report" 3 "22 Jun 2010" "Version 0.2" "EMMA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Report \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLOGGABLE\fP ()"
.br
.in -1c
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uip_ip6addr_t \fBhost\fP"
.br
.ti -1c
.RI "int \fBport\fP"
.br
.ti -1c
.RI "char \fBuri\fP [URI_OUTCOMMING_MAX_SIZE]"
.br
.ti -1c
.RI "char \fBmethod\fP"
.br
.ti -1c
.RI "char \fBbody\fP [BODY_NOTIFY]"
.br
.ti -1c
.RI "char \fBname\fP [RESSOURCE_NAME_SIZE]"
.br
.ti -1c
.RI "char \fBcondition\fP [REPORT_CMD_SIZE]"
.br
.ti -1c
.RI "int \fBPeriod\fP"
.br
.ti -1c
.RI "int \fBmin\fP"
.br
.ti -1c
.RI "int \fBmax\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 110 of file Emma-Rest6.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for EMMA from the source code.
