.TH "apps/Emma-Rest6/Rest6-Agent.c" 3 "22 Jun 2010" "Version 0.2" "EMMA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
apps/Emma-Rest6/Rest6-Agent.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Emma-Rest6.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBRESSOURCE_LIST_LOAD\fP (ressources_list)"
.br
.ti -1c
.RI "\fBRESSOURCES_INIT\fP ()"
.br
.ti -1c
.RI "\fBRESSOURCES_LOADER\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Example EMMA application 
.PP
\fBAuthor:\fP
.RS 4
Clement DUHART <duhart.clement@gmail.com> 
.RE
.PP

.PP
Definition in file \fBRest6-Agent.c\fP.
.SH "Author"
.PP 
Generated automatically by Doxygen for EMMA from the source code.
