<?xml version="1.0" encoding="UTF-8"?>
<simconf>
  <simulation>
    <title>Radio medium tests</title>
    <delaytime>0</delaytime>
    <randomseed>generated</randomseed>
    <motedelay_us>0</motedelay_us>
    <radiomedium>
      se.sics.mrm.MRM
      <rt_diffr_coefficient>-10.0</rt_diffr_coefficient>
      <bg_noise_var>1.0</bg_noise_var>
      <rt_max_diffractions>0</rt_max_diffractions>
      <snr_threshold>6.0</snr_threshold>
      <rt_max_reflections>1</rt_max_reflections>
      <tx_power>1.5</tx_power>
      <rx_antenna_gain>0.0</rx_antenna_gain>
      <apply_random>false</apply_random>
      <rt_ignore_non_direct>false</rt_ignore_non_direct>
      <rt_refrac_coefficient>-3.0</rt_refrac_coefficient>
      <rt_max_refractions>1</rt_max_refractions>
      <system_gain_var>4.0</system_gain_var>
      <rt_max_rays>1</rt_max_rays>
      <rt_disallow_direct_path>false</rt_disallow_direct_path>
      <rx_sensitivity>-100.0</rx_sensitivity>
      <obstacle_attenuation>-3.0</obstacle_attenuation>
      <rt_reflec_coefficient>-5.0</rt_reflec_coefficient>
      <bg_noise_mean>-150.0</bg_noise_mean>
      <rt_fspl_on_total_length>true</rt_fspl_on_total_length>
      <system_gain_mean>0.0</system_gain_mean>
      <tx_antenna_gain>0.0</tx_antenna_gain>
      <wavelength>0.346</wavelength>
      <obstacles />
    </radiomedium>
    <events>
      <logoutput>4000000</logoutput>
    </events>
    <motetype>
      se.sics.cooja.motes.ImportAppMoteType
      <identifier>apptype1</identifier>
      <description>Transmitter</description>
      <motepath>[CONFIG_DIR]</motepath>
      <moteclass>Transmitter</moteclass>
    </motetype>
    <motetype>
      se.sics.cooja.motes.ImportAppMoteType
      <identifier>apptype2</identifier>
      <description>Receiver</description>
      <motepath>[CONFIG_DIR]</motepath>
      <moteclass>Receiver</moteclass>
    </motetype>
    <motetype>
      se.sics.cooja.motes.ImportAppMoteType
      <identifier>apptype3</identifier>
      <description>Interferer</description>
      <motepath>[CONFIG_DIR]</motepath>
      <moteclass>Interferer</moteclass>
    </motetype>
    <motetype>
      se.sics.cooja.motes.ImportAppMoteType
      <identifier>apptype4</identifier>
      <description>Noise</description>
      <motepath>[CONFIG_DIR]</motepath>
      <moteclass>Noise</moteclass>
    </motetype>
    <mote>
      <interface_config>
        se.sics.cooja.motes.AbstractApplicationMoteType$SimpleMoteID
        <id>1</id>
      </interface_config>
      <interface_config>
        se.sics.cooja.interfaces.Position
        <x>0.0</x>
        <y>0.0</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>apptype1</motetype_identifier>
    </mote>
    <mote>
      <interface_config>
        se.sics.cooja.motes.AbstractApplicationMoteType$SimpleMoteID
        <id>2</id>
      </interface_config>
      <interface_config>
        se.sics.cooja.interfaces.Position
        <x>5000.0</x>
        <y>0.0</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>apptype2</motetype_identifier>
    </mote>
    <mote>
      <interface_config>
        se.sics.cooja.motes.AbstractApplicationMoteType$SimpleMoteID
        <id>3</id>
      </interface_config>
      <interface_config>
        se.sics.cooja.interfaces.Position
        <x>5000.0</x>
        <y>0.0</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>apptype3</motetype_identifier>
    </mote>
    <mote>
      <interface_config>
        se.sics.cooja.motes.AbstractApplicationMoteType$SimpleMoteID
        <id>4</id>
      </interface_config>
      <interface_config>
        se.sics.cooja.interfaces.Position
        <x>2500.0</x>
        <y>0.0</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>apptype4</motetype_identifier>
    </mote>
  </simulation>
  <plugin>
    se.sics.cooja.plugins.SimControl
    <width>259</width>
    <z>5</z>
    <height>205</height>
    <location_x>0</location_x>
    <location_y>0</location_y>
  </plugin>
  <plugin>
    se.sics.cooja.plugins.Visualizer
    <plugin_config>
      <skin>se.sics.cooja.plugins.skins.IDVisualizerSkin</skin>
      <skin>se.sics.cooja.plugins.skins.GridVisualizerSkin</skin>
      <skin>se.sics.cooja.plugins.skins.TrafficVisualizerSkin</skin>
      <skin>se.sics.cooja.plugins.skins.MoteTypeVisualizerSkin</skin>
      <viewport>0.07076395378267027 0.0 0.0 0.07076395378267027 320.29921347247466 70.26665503564911</viewport>
    </plugin_config>
    <width>1022</width>
    <z>0</z>
    <height>205</height>
    <location_x>258</location_x>
    <location_y>0</location_y>
  </plugin>
  <plugin>
    se.sics.cooja.plugins.LogListener
    <plugin_config>
      <filter />
      <coloring />
    </plugin_config>
    <width>1280</width>
    <z>6</z>
    <height>155</height>
    <location_x>0</location_x>
    <location_y>679</location_y>
  </plugin>
  <plugin>
    se.sics.cooja.plugins.TimeLine
    <plugin_config>
      <mote>0</mote>
      <mote>1</mote>
      <mote>2</mote>
      <mote>3</mote>
      <showRadioRXTX />
      <split>109</split>
      <zoomfactor>101.96280586710671</zoomfactor>
    </plugin_config>
    <width>1280</width>
    <z>4</z>
    <height>150</height>
    <location_x>1</location_x>
    <location_y>828</location_y>
  </plugin>
  <plugin>
    se.sics.cooja.plugins.RadioLogger
    <plugin_config>
      <split>150</split>
    </plugin_config>
    <width>646</width>
    <z>1</z>
    <height>265</height>
    <location_x>10</location_x>
    <location_y>406</location_y>
  </plugin>
  <plugin>
    se.sics.cooja.plugins.ScriptRunner
    <plugin_config>
      <scriptfile>[CONFIG_DIR]/testscript.js</scriptfile>
      <active>true</active>
    </plugin_config>
    <width>600</width>
    <z>3</z>
    <height>457</height>
    <location_x>665</location_x>
    <location_y>213</location_y>
  </plugin>
  <plugin>
    se.sics.cooja.plugins.MoteInterfaceViewer
    <mote_arg>1</mote_arg>
    <plugin_config>
      <interface>Position</interface>
      <scrollpos>0,0</scrollpos>
    </plugin_config>
    <width>350</width>
    <z>7</z>
    <height>300</height>
    <location_x>776</location_x>
    <location_y>228</location_y>
  </plugin>
  <plugin>
    se.sics.mrm.AreaViewer
    <plugin_config>
      <controls_visible>false</controls_visible>
      <zoom_x>0.06123557206489667</zoom_x>
      <zoom_y>0.06123557206489667</zoom_y>
      <pan_x>2200.1595722648212</pan_x>
      <pan_y>1216.5662793279093</pan_y>
      <show_background>true</show_background>
      <show_obstacles>true</show_obstacles>
      <show_channel>true</show_channel>
      <show_radios>true</show_radios>
      <show_activity>true</show_activity>
      <show_arrow>true</show_arrow>
      <vis_type>signalStrengthButton</vis_type>
      <resolution>100</resolution>
    </plugin_config>
    <width>639</width>
    <z>2</z>
    <height>188</height>
    <location_x>15</location_x>
    <location_y>211</location_y>
  </plugin>
</simconf>

