<?xml version="1.0" encoding="UTF-8"?>
<simconf>
  <simulation>
    <title>Radio medium tests</title>
    <delaytime>0</delaytime>
    <randomseed>generated</randomseed>
    <motedelay_us>0</motedelay_us>
    <radiomedium>
      se.sics.cooja.radiomediums.UDGM
      <transmitting_range>5500.0</transmitting_range>
      <interference_range>6000.0</interference_range>
      <success_ratio_tx>0.9</success_ratio_tx>
      <success_ratio_rx>0.5</success_ratio_rx>
    </radiomedium>
    <events>
      <logoutput>4000000</logoutput>
    </events>
    <motetype>
      se.sics.cooja.motes.ImportAppMoteType
      <identifier>apptype1</identifier>
      <description>Transmitter</description>
      <motepath>[CONFIG_DIR]</motepath>
      <moteclass>Transmitter</moteclass>
    </motetype>
    <motetype>
      se.sics.cooja.motes.ImportAppMoteType
      <identifier>apptype2</identifier>
      <description>Receiver</description>
      <motepath>[CONFIG_DIR]</motepath>
      <moteclass>Receiver</moteclass>
    </motetype>
    <motetype>
      se.sics.cooja.motes.ImportAppMoteType
      <identifier>apptype3</identifier>
      <description>Interferer</description>
      <motepath>[CONFIG_DIR]</motepath>
      <moteclass>Interferer</moteclass>
    </motetype>
    <motetype>
      se.sics.cooja.motes.ImportAppMoteType
      <identifier>apptype4</identifier>
      <description>Noise</description>
      <motepath>[CONFIG_DIR]</motepath>
      <moteclass>Noise</moteclass>
    </motetype>
    <mote>
      <interface_config>
        se.sics.cooja.motes.AbstractApplicationMoteType$SimpleMoteID
        <id>1</id>
      </interface_config>
      <interface_config>
        se.sics.cooja.interfaces.Position
        <x>0.0</x>
        <y>0.0</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>apptype1</motetype_identifier>
    </mote>
    <mote>
      <interface_config>
        se.sics.cooja.motes.AbstractApplicationMoteType$SimpleMoteID
        <id>2</id>
      </interface_config>
      <interface_config>
        se.sics.cooja.interfaces.Position
        <x>5000.0</x>
        <y>0.0</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>apptype2</motetype_identifier>
    </mote>
    <mote>
      <interface_config>
        se.sics.cooja.motes.AbstractApplicationMoteType$SimpleMoteID
        <id>3</id>
      </interface_config>
      <interface_config>
        se.sics.cooja.interfaces.Position
        <x>5000.0</x>
        <y>0.0</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>apptype3</motetype_identifier>
    </mote>
    <mote>
      <interface_config>
        se.sics.cooja.motes.AbstractApplicationMoteType$SimpleMoteID
        <id>4</id>
      </interface_config>
      <interface_config>
        se.sics.cooja.interfaces.Position
        <x>2500.0</x>
        <y>0.0</y>
        <z>0.0</z>
      </interface_config>
      <motetype_identifier>apptype4</motetype_identifier>
    </mote>
  </simulation>
  <plugin>
    se.sics.cooja.plugins.SimControl
    <width>259</width>
    <z>4</z>
    <height>205</height>
    <location_x>0</location_x>
    <location_y>0</location_y>
  </plugin>
  <plugin>
    se.sics.cooja.plugins.Visualizer
    <plugin_config>
      <skin>se.sics.cooja.plugins.skins.IDVisualizerSkin</skin>
      <skin>se.sics.cooja.plugins.skins.GridVisualizerSkin</skin>
      <skin>se.sics.cooja.plugins.skins.TrafficVisualizerSkin</skin>
      <skin>se.sics.cooja.plugins.skins.MoteTypeVisualizerSkin</skin>
      <skin>se.sics.cooja.plugins.skins.UDGMVisualizerSkin</skin>
      <viewport>0.07076395378267027 0.0 0.0 0.07076395378267027 320.29921347247466 70.26665503564911</viewport>
    </plugin_config>
    <width>1022</width>
    <z>0</z>
    <height>205</height>
    <location_x>258</location_x>
    <location_y>0</location_y>
  </plugin>
  <plugin>
    se.sics.cooja.plugins.LogListener
    <plugin_config>
      <filter />
      <coloring />
    </plugin_config>
    <width>1280</width>
    <z>5</z>
    <height>155</height>
    <location_x>0</location_x>
    <location_y>679</location_y>
  </plugin>
  <plugin>
    se.sics.cooja.plugins.TimeLine
    <plugin_config>
      <mote>0</mote>
      <mote>1</mote>
      <mote>2</mote>
      <mote>3</mote>
      <showRadioRXTX />
      <split>109</split>
      <zoomfactor>101.96280586710671</zoomfactor>
    </plugin_config>
    <width>1280</width>
    <z>3</z>
    <height>150</height>
    <location_x>1</location_x>
    <location_y>828</location_y>
  </plugin>
  <plugin>
    se.sics.cooja.plugins.RadioLogger
    <plugin_config>
      <split>150</split>
    </plugin_config>
    <width>646</width>
    <z>1</z>
    <height>265</height>
    <location_x>10</location_x>
    <location_y>406</location_y>
  </plugin>
  <plugin>
    se.sics.cooja.plugins.ScriptRunner
    <plugin_config>
      <scriptfile>[CONFIG_DIR]/testscript.js</scriptfile>
      <active>true</active>
    </plugin_config>
    <width>600</width>
    <z>2</z>
    <height>457</height>
    <location_x>665</location_x>
    <location_y>213</location_y>
  </plugin>
</simconf>

