
###stm32w port will only compile with UIP_CONF_IPV6=1 now
UIP_CONF_IPV6=1

all:  tcp-client tcp-client-psock tcp-server tcp-server-multiconn \
	tcp-server-multiconn-psock tcp-server-psock

CONTIKI = ../..
include $(CONTIKI)/Makefile.include
